In [1]:
import numpy as np


In [6]:
documents="""
simple example with cats and dogs 
another simple example with dogs and cats
another simple example with mouse and cheese
""".split("\n")[1:-1]

In [7]:
documents

['simple example with cats and dogs ',
 'another simple example with dogs and cats',
 'another simple example with mouse and cheese']

In [9]:
la=documents[0].lower().split()
lb=documents[1].lower().split()
lc=documents[2].lower().split()

In [11]:
word_dict=set(la).union(set(lb)).union(set(lc))

In [12]:
word_dict

{'and',
 'another',
 'cats',
 'cheese',
 'dogs',
 'example',
 'mouse',
 'simple',
 'with'}

In [13]:
word_dict_A=dict.fromkeys(word_dict,0)
word_dict_B=dict.fromkeys(word_dict,0)
word_dict_C=dict.fromkeys(word_dict,0)

In [14]:
for word in la:
    word_dict_A[word]+=1
for word in lb:
    word_dict_B[word]+=1
for word in lc:
    word_dict_C[word]+=1

In [17]:
def computetf(wordDict,bgofwords):
    n=len(bgofwords)
    tfdict={}
    for word ,count in wordDict.items():
        tfdict[word]=count/float(n)
    return tfdict


In [19]:
tfa=computetf(word_dict_A,la)
tfb=computetf(word_dict_B,lb)
tfc=computetf(word_dict_C,lc)

In [22]:
def computeidf(docs):
    import math
    idfdict=dict.fromkeys(docs[0].keys(),0)
    n=len(docs)
    for doc in docs:
        for word,val in doc.items():
            if val>0:
                idfdict[word]+=1
    for word,val in idfdict.items():
        idfdict[word]=math.log(n/float(val))
    return idfdict
    

In [26]:
idf=computeidf([word_dict_A,word_dict_B,word_dict_C])

In [27]:
def computetfidf(tf,idf):
    tfidf={}
    for word,val in tf.items():
        tfidf[word]=val*idf[word]
    return tfidf

In [28]:
computetfidf(tfa,idf)

{'example': 0.0,
 'another': 0.0,
 'and': 0.0,
 'cats': 0.06757751801802739,
 'with': 0.0,
 'dogs': 0.06757751801802739,
 'cheese': 0.0,
 'simple': 0.0,
 'mouse': 0.0}

In [62]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score

docs="""
Food is an essential part of human life, and its production and distribution have been impacted by wars throughout history. Wars have not only disrupted the food supply but have also influenced our cultural relationship with food. In this article, we explore how conflicts shape our relationship with food and the stories behind them.
Food as a Weapon of War
Throughout history, food has been used as a weapon of war. During times of conflict, armies often targeted crops and livestock to deprive their enemies of food. This tactic was used during the American Civil War when Union troops destroyed crops and livestock to weaken the Confederacy's food supply.
In more recent times, food has been used as a tool of political manipulation. During the Cold War, the Soviet Union used its control of the food supply to exert influence over Eastern Europe. In Cuba, the United States imposed a trade embargo in 1960 that limited the country's access to food, medicine, and other essential goods.
Food as a Symbol of Resistance
In many conflicts, food has become a symbol of resistance. In the Palestinian territories, falafel, hummus, and other traditional foods have become symbols of Palestinian identity and resistance against Israeli occupation. During the Algerian War of Independence, traditional Algerian cuisine was used to assert national identity and promote resistance against French colonialism.
Food has also played a role in civil rights movements. In the United States, sit-ins at lunch counters were a key part of the civil rights movement. These sit-ins were used to protest segregation in public places, including restaurants. Food was used as a symbol of equality, and the act of sharing a meal became a powerful tool for social change.
Food as a Comfort in Times of War
In times of war, food can provide comfort and a sense of normalcy. Soldiers on the front lines often receive care packages from home, which include food and other comforts. During World War II, the United States launched a massive effort to send care packages to soldiers, which included canned goods, candy, and cigarettes.
Food can also provide comfort to civilians affected by war. In areas of conflict, food aid is often distributed to those in need. In Syria, for example, organizations such as the World Food Programme provide food assistance to millions of people affected by the ongoing conflict.
Food as a Cultural Bridge
Despite the impact of war on food, it can also serve as a cultural bridge. Food has the power to bring people together, even in times of conflict. In Israel and Palestine, joint cooking programs bring Jewish and Arab women together to share traditional recipes and stories. In Afghanistan, the organization Bamiyan Cultural Centre brings together people from different ethnic and religious backgrounds to share meals and cultural traditions.
Conclusion
Food and war are intertwined in complex ways. Conflicts have impacted the food supply, influenced our cultural relationship with food, and even led to the use of food as a weapon of war. Despite this, food also has the power to provide comfort, serve as a symbol of resistance, and bridge cultural divides. The stories behind food and war remind us of the importance of food in our lives and the need for compassion and understanding in times of conflict
""".split("\n")[1:-1]

In [63]:
docs

['Food is an essential part of human life, and its production and distribution have been impacted by wars throughout history. Wars have not only disrupted the food supply but have also influenced our cultural relationship with food. In this article, we explore how conflicts shape our relationship with food and the stories behind them.',
 'Food as a Weapon of War',
 "Throughout history, food has been used as a weapon of war. During times of conflict, armies often targeted crops and livestock to deprive their enemies of food. This tactic was used during the American Civil War when Union troops destroyed crops and livestock to weaken the Confederacy's food supply.",
 "In more recent times, food has been used as a tool of political manipulation. During the Cold War, the Soviet Union used its control of the food supply to exert influence over Eastern Europe. In Cuba, the United States imposed a trade embargo in 1960 that limited the country's access to food, medicine, and other essential go

In [73]:
vec=TfidfVectorizer(stop_words="english")
x=vec.fit_transform(docs)

In [74]:
x.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.79595181, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.15076725, 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.1541455 ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.13584616, 0.        ,
        0.        ]])

In [75]:
terms=vec.get_feature_names_out()
terms

array(['1960', 'access', 'act', 'affected', 'afghanistan', 'aid',
       'algerian', 'american', 'arab', 'areas', 'armies', 'article',
       'assert', 'assistance', 'backgrounds', 'bamiyan', 'bridge',
       'bring', 'brings', 'candy', 'canned', 'care', 'centre', 'change',
       'cigarettes', 'civil', 'civilians', 'cold', 'colonialism',
       'comfort', 'comforts', 'compassion', 'complex', 'conclusion',
       'confederacy', 'conflict', 'conflicts', 'control', 'cooking',
       'counters', 'country', 'crops', 'cuba', 'cuisine', 'cultural',
       'deprive', 'despite', 'destroyed', 'different', 'disrupted',
       'distributed', 'distribution', 'divides', 'eastern', 'effort',
       'embargo', 'enemies', 'equality', 'essential', 'ethnic', 'europe',
       'example', 'exert', 'explore', 'falafel', 'food', 'foods',
       'french', 'goods', 'history', 'home', 'human', 'hummus',
       'identity', 'ii', 'impact', 'impacted', 'importance', 'imposed',
       'include', 'included', 'includ

In [112]:
model=KMeans(init="k-means++",max_iter=500)

In [113]:
model.fit(x)

KMeans(max_iter=500)

In [114]:
order=model.cluster_centers_.argsort()[:,::-1]
order

array([[172,  29, 161, ..., 105, 104,   0],
       [137, 155,  65, ..., 109, 107,   0],
       [ 44,  16,  65, ..., 107, 106,   0],
       ...,
       [  3, 129,  65, ..., 111, 110,   0],
       [ 65, 176, 172, ..., 105, 104,   0],
       [171,  65,  95, ..., 109, 108,  89]], dtype=int64)

In [130]:
for i in range(8):
    print(i)
    for ind in order[i,:1]:
        print(terms[ind])
    print("------------------------")

0
war
------------------------
1
resistance
------------------------
2
cultural
------------------------
3
sit
------------------------
4
conclusion
------------------------
5
affected
------------------------
6
food
------------------------
7
used
------------------------


In [131]:
text="food"
y=vec.transform([text])

In [132]:
model.predict(y)

array([6])